cron_hn_crawler:
  # cron: "*/1 * * * *"
  cron: "0 2 * * *"
  class: "HnCrawlerWorker"
  queue: cron_fetch_from_hackernews_at_2am
cron_reddit_crawler:
  cron: "20 2 * * *"
  class: "RedditCrawlerWorker"
  queue: cron_fetch_from_reddit_at_2:20am
cron_quora_crawler:
  cron: "40 2 * * *"
  class: "QuoraCrawlerWorker"
  queue: cron_fetch_from_quora_at_2:40am
cron_user_mailer:
  # cron: "*/2 * * * *"
  cron: "0 5 * * *"
  class: "FeedMailerWorker"
  queue: cron_send_daily_feeds_at_5am
