cron_hn_crawler:
  # cron: "*/1 * * * *"
  cron: "0 2 * * *"
  class: "HnCrawlerWorker"
  queue: cron_fetch_from_hackernews_at_2am
cron_user_mailer:
  # cron: "*/2 * * * *"
  cron: "0 5 * * *"
  class: "FeedMailerWorker"
  queue: cron_send_daily_feeds_at_5am
