---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
staging:
  :concurrency: 10
production:
  :concurrency: 10
queues:
  - default
  - cron_fetch_from_hackernews_at_2am
  - cron_fetch_from_reddit_at_2:20am
  - cron_fetch_from_quora_at_2:40am
  - cron_send_daily_feeds_at_5am
  - confirmations_mailers